<a href="https://colab.research.google.com/github/Rinumounika/Breast-cancer-detection-using-Machine-Learning/blob/Test/Week_1_Breast_Cancer_detection_proejct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Q1. Create an array having consecutive natural numbers of size 6x3 and print it.

import numpy as np

arr1 = np.arange(18).reshape(6, 3)
print("arr1:{}".format(arr1))

arr1:[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [0]:
import pandas as pd
df=pd.read_csv(r"/content/sample_data/california_housing_test.csv")

#Q2: Rename alll the coumns in the dataset as per your wish and save it in another dataframe and name it df2
df2=df.rename(columns={"Name":"Full_name","Income per month":"Monthly_Income","State":"State_name","Age":"Total_age","Sex":"Sex(F/M)","Number of siblings":"Total_siblings"})
df2.info()

In [0]:
#Q3: After you have created df2, make the same changes in the original dataframe using the inplace
df.rename(columns={"Name":"Full_name","Income per month":"Monthly_Income","State":"State_name","Age":"Total_age","Sex":"Sex(F/M)","Number of siblings":"Total_siblings"},inplace=True)
df

In [0]:
#Q4: Show only the columns information, sex and number of siblings.
df[["Sex(F/M)","Total_siblings"]]

In [0]:
#Q5: Use iloc method to print data from column 1 to 4 and rows 3 to 9
df.iloc[0:3,0:3]