<a href="https://colab.research.google.com/github/Rinumounika/Breast-cancer-detection-using-Machine-Learning/blob/master/Week_1_Breast_Cancer_detection_proejct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Q1. Create an array having consecutive natural numbers of size 6x3 and print it.

import numpy as np

arr1 = np.arange(18).reshape(6, 3)
print("arr1:{}".format(arr1))

arr1:[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [1]:
import pandas as pd
df=pd.read_excel(r"/content/Week 1 Dataset.xlsx")

#Q2: Rename alll the coumns in the dataset as per your wish and save it in another dataframe and name it df2
df2=df.rename(columns={"Name":"Full_name","Income per month":"Monthly_Income","State":"State_name","Age":"Total_age","Sex":"Sex(F/M)","Number of siblings":"Total_siblings"})
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Full_name       10 non-null     object
 1   Monthly_Income  10 non-null     int64 
 2   State_name      10 non-null     object
 3   Total_age       10 non-null     int64 
 4   Sex(F/M)        10 non-null     object
 5   Total_siblings  10 non-null     int64 
dtypes: int64(3), object(3)
memory usage: 608.0+ bytes


In [0]:
#Q3: After you have created df2, make the same changes in the original dataframe using the inplace
df.rename(columns={"Name":"Full_name","Income per month":"Monthly_Income","State":"State_name","Age":"Total_age","Sex":"Sex(F/M)","Number of siblings":"Total_siblings"},inplace=True)
df

Full_name  Monthly_Income     State_name  Total_age Sex(F/M)  Total_siblings
0         A              50     Tamil Nadu         23        M               0
1         B              34      Karnataka         37        F               3
2         C              54     Tamil Nadu         35        F               1
3         D              24  Uttar Pradesh         26        F               4
4         E              19          Bihar         59        M               5
5         F              21          Bihar         48        M               6
6         G              40          Delhi         30        F               2
7         H              20  Uttar Pradesh         72        M              10
8         I              30      Telangana         22        F               0
9         J              18    Chattisgarh         42        M               7

In [0]:
#Q4: Show only the columns information, sex and number of siblings.
df[["Sex(F/M)","Total_siblings"]]

Sex(F/M)  Total_siblings
0        M               0
1        F               3
2        F               1
3        F               4
4        M               5
5        M               6
6        F               2
7        M              10
8        F               0
9        M               7

In [0]:
#Q5: Use iloc method to print data from column 1 to 4 and rows 3 to 9
df.iloc[3:10,0:4]

Full_name  Monthly_Income     State_name  Total_age
3         D              24  Uttar Pradesh         26
4         E              19          Bihar         59
5         F              21          Bihar         48
6         G              40          Delhi         30
7         H              20  Uttar Pradesh         72
8         I              30      Telangana         22
9         J              18    Chattisgarh         42

In [0]:
#Q6: Find the total value count of number of siblings in the given dataset
#df["Total_siblings"].count()
df["Total_siblings"].value_counts()

0     2
10    1
7     1
6     1
5     1
4     1
3     1
2     1
1     1
Name: Total_siblings, dtype: int64

#Q7: What are dependent and independent varibles in our dataset?
Independent variables: Monthly_Income,Total_age	
Dependent variables:Total_siblings

Q8: Mention all your finding from the above given heatmap.

From the given heatmap, we have conclude that age and Number of siblings are strongly correlated which tends to increase in age increases no of siblings. Income per moth and number of siblings are most weakly correlated so increase in income per month decreases number of siblings. Even age and income per month are weakly correlated.